baseURL = "https://nhoya.github.io"
languageCode = "en-us"
title = "0x7a"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true

paginate = 5
Copyright = "All rights reserved - 2018"
canonifyurls = true

[params]
	logo = "img/cat.jpg"
	favicon = "img/favicon.ico"
	socialShare = true
[Author]
  name = "Francesco Giordano"
  website = ""
  github = "Nhoya"
  twitter = "0x7a657461"
  paypal = "nhoya"

[[menu.main]]
    name = "About Me"
    url = "page/about"
    weight = 4

[[menu.main]]
    identifier = "ctf"
    name = "CTF"
    weight = 1

[[menu.main]]
    parent = "ctf"
    name = "JBZ Team"
    url = "https://jbzteam.github.io"
    weight = 1

[[menu.main]]
    parent = "ctf"
    name = "capturetheflag.it"
    url = "https://capturetheflag.it"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "gOSINT"
    url = "https://github.com/Nhoya/gOSINT"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "SplitShare"
    url = "https://github.com/Nhoya/SplitShare"
    weight = 2

[[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    weight = 3

[[menu.main]]
    parent = "writeups"
    name = "Pastebin and Reddit Markdown XSS"
    url = "post/pastebin-reddit-xss/"
    weight = 1

[[menu.main]]
    parent = "writeups"
    name = "Mycroft AI \"Zero Click\" Remote Code Execution"
    url = "post/mycroftai-rce"
    weight = 2

[[menu.main]]
    identifier = "feeds"
    name = "My Feeds"
    weight = 4

[[menu.main]]
    parent = "feeds"
    name = "Orange Tsai"
    url = "https://blog.orange.tw"
    weight = 2

[[menu.main]]
    parent = "feeds"
    name = "x0rz"
    url = "https://0day.rocks"
    weight = 3

[[menu.main]]
    parent = "feeds"
    name = "P=NP"
    url = "https://pequalsnp-team.github.io"
    weight = 1    
